export const productsArray = [
  {
    id: 1,
    left: true,
    title: "CLASIC EXTENSION, FUNDAMENTAL COURSE",
    category: "Eyelash Extension",
    imageUrl: "/images/new/img1.png",
    price: "3000 AED",
    duration: " 3 days, 6 hours/per day (total: 18 hours)",
    desc: "The most practical course of three days aimed at studying eyelash extension and eye modeling technology. The theory is divided into blocks for the best understanding and assimilation. Practice is immediately given after studying theory. Practical eyelash extension training on the models. The certificate is issued after completing the course.",
    content: [
      {
        theory:
          "Natural eyelashes: stages of growth, renewal, building and structure. Detailed review of materials for eyelash extension. Eyelash Extension procedure stages. ",
        practice:
          "Practical exercises for development of fine hand movements without models. Tutor-led model training. ",
        homework:
          "The homework is given to you between classes to learn more quickly how to work with eyelashes and tweezers. After the task, practice on the model on the 2nd day is 75% more effective than without developing muscle memory during the task. ",
      },
      {
        theory:
          "Eyelash refill and eyelash removal. Eyelash setting techniques. Indent, contact area, direction of the eyelashes. Patches work without red eyes. Glue types. Working with anagen. ",
        practice:
          "Checkup of all preparatory stages. Tutor-led eyelash extension. Checking for gluing and coupling quality. Point removal. ",
        homework:
          "2 tasks, that are aimed at training glue control, eyelash separation, different technique of eyelash setting, checking and separation of glues, creating an equal indent. ",
      },
      {
        theory:
          "Working with corners;  Customer face analysis; Review of modelling tools: effects, curves, colour, volume; Allergies, contraindications; Aftercare. Fill-in of the modeling checklist; Model face analysis.",
        practice:
          "Full eyelash extension procedure with all phases” from A to Z” on the model.",
      },
    ],
    certificate:
      "At the end of the course, you will receive a certificate that you have successfully completed the course on eyelash extension and acquired the necessary skills in practical work. ",
    get: "Methodical materials: All the theory you will learn in the course will be available to you after completing the course. ",
  },
  {
    id: 2,
    right: true,
    title: "Volume, upgraded course",
    category: "Eyelash Extension",
    imageUrl: "/images/new/img2.png",
    price: "1000 AED",
    duration: "1 day/ 8 hours",
    desc: "This course is for you if: You do not know how to do the volume and want to learn; Can only do 2 or 3d and want to learn more; You want to fix the problems in volumetric expansion; Want to make the volumetric expansion faster, learn new techniques; ",
    content: [
      {
        theory:
          "Volume eyelash extension: when to apply. Volumetric beam formation techniques. Detailed review of beam forming techniques.",
        practice:
          "Beam forming work without model. Select the effect for the model. Volume eyelash extension on the model",
      },
    ],
    certificate:
      "At the end of the course, you will receive a certificate that you have successfully completed the course on eyelash extension and acquired the necessary skills in practical work. ",
    get: "Methodical materials: All the theory you will learn in the course will be available to you after completing the course on volume eyelash extension. Advanced training course for masters who already know classical eyelash extension without any mistakes and want to move on. On the course all techniques of beam formation are explained, especially gluing, direction in volumetric expansion, work with glue, geometry of beams, problems and mistakes in the formation and production of beams. ",
  },
  {
    id: 3,
    left: true,
    title: "Kardashian Effect  ",
    category: "Eyelash Extension",
    imageUrl: "/images/new/img3.png",
    price: "1000 AED",
    duration: "1 day/ 8 hours",
    desc: "What do Kardashian eyelash extensions look like? Kardashian eyelash extensions are similar to Hybrid eyelash extensions because both variations require a mixture of Classic and Russian Volume lashes. In the case of hybrid eyelash extensions, 30% of the individual extensions are Classic. whilst the remaining 70% are Russian Volume The result is beautiful, voluminous lashes, without the unnatural look which only using Russian Volume Lash extensions often creates. The lash line also appears thicker and solid, which is what makes the eyelashes appear so full. Whilst hybrid lash extensions are a great look, the voluminous, yet the soft appearance of Kardashian lashes will really make your eyes pop.",
  },
  {
    id: 4,
    right: true,
    title: "Wet Effect",
    category: "Eyelash Extension",
    imageUrl: "/images/new/img4.png",
    price: "1000 AED",
    duration: "1 day/ 8 hours",
    desc: "What are wet look eyelashes? Wet look lashes are created essentially from using lighter lashes to create narrow, pretty much closed fans, which should be applied to individual lashes to achieve the desired effect. ",
  },
  {
    id: 5,
    left: true,
    title: "Eyeliner Effect  ",
    category: "Eyelash Extension",
    imageUrl: "/images/new/img5.png",
    price: "1000 AED",
    duration: "1 day/ 8 hours",
    desc: "What is eyeliner effect lashes? This is state-of-the-art technology, when several very thin separate extensions are picked manually into the lash fan and wrapped around the natural lash using a special technique that ensures a very strong and long-lasting bond. ",
  },
  {
    id: 6,
    right: true,
    title: "Colored Lashes ",
    category: "Eyelash Extension",
    imageUrl: "/images/new/img6.png",
    price: "1000 AED",
    duration: "1 day/ 8 hours",
    desc: "Some daring beauty buffs are taking their love for false lashes to next level — with colored falsies. Just peep Instagram for proof, and you'll find a plethora of false-lash looks in almost every color imaginable. Pink, purple, blue ",
  },
  {
    id: 7,
    left: true,
    slideImg1: "/images/new/slideImg1.png",
    title: "Eyeliner + Lips shading course",
    category: "SEMI PERMANENT MAKEUP",
    imageUrl: "/images/new/img7.png",
    price: "3000 AED",
    duration: "3 days 12 hours",
    desc: "Some daring beauty buffs are taking their love for false lashes to next level — with colored falsies. Just peep Instagram for proof, and you'll find a plethora of false-lash looks in almost every color imaginable. Pink, purple, blue ",
    content: [
      {
        time: "4 hours (3h theory 1h practice)",
        list: [
          "Basic knowledge permanent make up such as:",
          "Skin structure",
          "Equipment",
          "Aseptic and antiseptic",
          "Practice on latex ",
          "Home tasks",
        ],
      },
      {
        desc: "EYELINER Course",
        time: "8 hours (4h theory 4h practice) ",
        list: [
          "Step-by-step instructions for working with a client",
          "Makeup with different types of faces ",
          "Sketching eyeliner ",
          "Contraindications",
          "Procedure for injecting pigment into the eye ",
          "Hand position",
          "Practice eyeliner providing 1 model",
        ],
      },
      {
        desc: "LIPS SHADING Course ",
        time: "8 hours (4h theory 4h practice) ",
        list: [
          "Sketching lips",
          "Basic principles work with lips ",
          "Coloring",
          "Procedure for injecting pigment into the lips ",
          "Hand position ",
          "Practice lips shading providing 1 model ",
        ],
      },
    ],
  },
  {
    id: 8,
    right: true,
    title: "MICROSHADING EYEBROWS intensive COURSE ",
    category: "SEMI PERMANENT MAKEUP",
    imageUrl: "/images/new/img8.png",
    price: "5000 AED",
    duration: "3 days 18 hours",
    desc: "	CERTIFECATE provide and 1 MODEL provide",
    content: [
      {
        time: "8 hours (6h theory 2h practice) ",
        list: [
          "Basic knowledge permanent make up (SPMU) such as: ",
          "Skin structure",
          "Equipment and cabinet SPMU artist ",
          "Aseptic and antiseptic ",
          "Makeup eyebrows with different types of faces ",
          "Sketching eyebrows ",
          "Contraindications",
          "	Practice on latex",
          "Home tasks",
        ],
      },
      {
        time: "10 hours (6h theory 4h demo)",
        list: [
          "Homework check, working on mistakes",
          "	Step-by-step instructions for working with a client A-Z  ",
          "Procedure for injecting pigment into the eyebrow",
          "Hand position",
          "Demonstration on-live model ",
          "Discussion of the process, answer to questions",
        ],
      },
      {
        time: "10 hours (3h theory 7h )",
        list: ["Skin color and coloring", "Student practice on model", "Exams"],
      },
    ],
  },
  {
    id: 9,
    left: true,
    title: "MANICURE COURSE, BEGGINER",
    category: "NAILS",
    imageUrl: "/images/new/img9.png",
    price: "5000 AED",
    duration: "5 days, 6 hours/day (total: 24 hours) ",
    manage: {
      title: "Nails Structure & Functions of management",
      list: [
        "Consultation",
        "Indications & contraindications",
        "Trolley setting ",
        "Equipment & materials knowledge",
        "Treatment plan",
        "Nails structure & functions of management",
        "Step by step procedure ",
        "Nail polish application ",
        "Hand & foot massage ",
        "Gelish manicure and pedicure ",
        "Sterilization and sanitization of tools ",
        "Use of drill machine for advance treatments ",
        "How to prepare self as an manicurist ",
        "Home care advice  ",
      ],
    },
    content: [
      {
        title: "Theory",
        list: [
          "Nail structure",
          "Sterilization of instruments",
          "Diseases and pathology of nails",
          "Tools and equipment",
          "Hardware manicure",
          "Coating",
        ],
      },
      {
        title: "Practice 1 after theory same day ",
        list: [
          "Handling your left hand (practice)",
          "4 days full practice with models",
        ],
      },
    ],
    certificate:
      "At the end of the course, you will receive a certificate that you have successfully completed the course on manicure and acquired the necessary skills in practical work.",
    kit: [
      "Tools (fails, buffers, shine buffers, scissors, pusher) ",
      "Cutters (carbide, titanium, diamond, ceramic) ",
      "Preparation for disinfection",
      "For coating (base coat, rubber base, color gel, top coat) ",
      "UV/UF Lamp ",
      "Nail drill machine ",
      "For preparing nail plate nail fresher and ultra bond (primer) ",
      "Nail polish remover pads ",
      "Protect glasses ",
      "Brushes for designs ",
      "Face masks ",
      "Nail polish removal ",
      "Disposable towels ",
      "Led lamp for table ",
      "Manicure desk (chairs) ",
    ],
  },
  {
    id: 10,
    right: true,
    title: "SMART PEDICURE COURSE",
    category: "NAILS",
    imageUrl: "/images/new/img10.png",
    price: "1500 AED",
    duration: "1 days, 6-7 hours/day (total: 6-7 hours)",
    manage: {
      title: "Smart pedicure & Functions of management",
      list: [
        "Complete theory of structure of & its disorders  ",
        "Products knowledge ",
        "Clients consultation to understand their occupation/lifestyle ",
        "Client preparation ",
        "Preparing work station ",
        "Smart pedicure  ",
        "Application steps & removal steps ",
        "Nail polish application & after care suggestion ",
        "Practice on dummy and live clients usage of drill machine ",
        "Home care advice  ",
      ],
    },
    content: [
      {
        title: "Theory",
        list: [
          "Top nails molds ",
          "Poly gel ",
          "Brushes and tools ",
          "Detachments and chips ",
          "Architecture ",
          "Layout of material ",
          "Failing forms (modeling) ",
        ],
      },
      {
        title: "Practice 1 after theory same day ",
        list: [
          "Handling your left hand (practice)",
          "4 days full practice with models ",
        ],
      },
    ],
    certificate:
      "At the end of the course, you will receive a certificate that you have successfully completed the course on nail extension  and acquired the necessary skills in practical work.",
    kit: [
      "Tools (fails, smart disk, buffers, shine buffers, scissors, pusher) ",
      "Cutters (carbide, titanium, diamond, ceramic) ",
      "Preparation for disinfection ",
      "For coating (base coat, rubber base, poly gel, color gel, top coat) ",
      "UV/UF Lamp ",
      "Nail drill machine ",
      "For preparing nail plate nail fresher and ultra bond (primer) ",
      "Nail polish remover pads ",
      "Protect glasses ",
      "Brushes for designs ",
      "Face masks ",
    ],
  },
];
